version: "0.2"
ignorePaths:
  - .github/badges/*.svg
  - .gitignore
dictionaryDefinitions: []
dictionaries: []
words:
  - argparse
  - autodoc
  - charliermarsh
  - CIRA
  - copybutton
  - dateparser
  - docstrings
  - Dunder
  - esbenp
  - geoips
  - gethostname
  - groupindex
  - himawari
  - IODC
  - isort
  - kwargs
  - lextudio
  - matangover
  - mccabe
  - Meso
  - meteosat
  - Mypy
  - mypy
  - newhost
  - newplatform
  - njpwerner
  - NOAA
  - numpy
  - pathlib
  - Pepy
  - pinkrst
  - pycodestyle
  - pydantic
  - pydocstyle
  - Pyflakes
  - Pylint
  - pypa
  - PYPI
  - pypi
  - pycon
  - pyproject
  - pytest
  - Pytest
  - pythonpath
  - pyupgrade
  - pyyaml
  - rabbitmq
  - rabbitmqhost
  - sdist
  - serialisation
  - Serialisation
  - seviri
  - singularised
  - snekvik
  - sphinxarg
  - tamasfe
  - testhost
  - trond
  - tryceratops
  - typehints
  - typer
  - Uttmark
  - viewcode
  - xarray
  - yday
ignoreWords:
  - addopts
  - aeiou
  - brightgreen
  - genbadge
  - glas
  - jpetrucciani
  - junitxml
  - norecursedirs
  - oneline
  - outdirs
  - repr
  - retval
  - runcmd
  - sphinxcontrib
  - sses
  - testpaths
  - venv
  - xdist
  - zzes
import: []
